package vlsi.routing.design.ui;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileFilter;

import vlsi.routing.design.process.MixedRouterProcess;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class MixedRouterFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form MixedRouterFrame
     */
    public MixedRouterFrame() {
    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setTitle("MixedRouter");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initComponents() {

        famePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filenameTextfield = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter the file: ");

        filenameTextfield.setText("");

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout famePanelLayout = new javax.swing.GroupLayout(famePanel);
        famePanel.setLayout(famePanelLayout);
        famePanelLayout.setHorizontalGroup(
            famePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, famePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(famePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(famePanelLayout.createSequentialGroup()
                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, Short.MAX_VALUE))
                    .addComponent(filenameTextfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browseButton)
                .addGap(35, 35, 35))
        );
        famePanelLayout.setVerticalGroup(
            famePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(famePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(famePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filenameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addGroup(famePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateButton)
                    .addComponent(closeButton))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(famePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(famePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                       

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
       MixedRouterFrame.this.dispose();
    }                                           

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
       MixedRouterProcess mixedRouter = new MixedRouterProcess();
       mixedRouter.setInpGRFileName(filenameTextfield.getText());
       mixedRouter.implementRouter();
    }                                              

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
       	JFileChooser inpPlaFileChooser;
		if (filenameTextfield.getText().equals(""))
			inpPlaFileChooser = new JFileChooser();
		else
			inpPlaFileChooser = new JFileChooser(filenameTextfield.getText());

		inpPlaFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

		inpPlaFileChooser.setFileFilter(new FileFilter() {
			public boolean accept(File f) {
				return f.getName().toLowerCase().endsWith(".gr")
						|| f.isDirectory();
			}

			public String getDescription() {
				return "*.gr";
			}
		});
		int returnVal = inpPlaFileChooser.showOpenDialog(MixedRouterFrame.this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			// File file = inpPlaFile.getSelectedFile();
			filenameTextfield.setText(inpPlaFileChooser.getSelectedFile()
					.getAbsolutePath());
			//errorLabel.setText("");
		}
    }                                            

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify                     
    private javax.swing.JButton browseButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel famePanel;
    private javax.swing.JTextField filenameTextfield;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
